export const KENYA_COUNTIES = [
  'Baringo',
  'Bomet',
  'Bungoma',
  'Busia',
  'Elgeyo-Marakwet',
  'Embu',
  'Garissa',
  'Homa Bay',
  'Isiolo',
  'Kajiado',
  'Kakamega',
  'Kericho',
  'Kiambu',
  'Kilifi',
  'Kirinyaga',
  'Kisii',
  'Kisumu',
  'Kitui',
  'Kwale',
  'Laikipia',
  'Lamu',
  'Machakos',
  'Makueni',
  'Mandera',
  'Marsabit',
  'Meru',
  'Migori',
  'Mombasa',
  "Murang'a",
  'Nairobi',
  'Nakuru',
  'Nandi',
  'Narok',
  'Nyamira',
  'Nyandarua',
  'Nyeri',
  'Samburu',
  'Siaya',
  'Taita-Taveta',
  'Tana River',
  'Tharaka-Nithi',
  'Trans Nzoia',
  'Turkana',
  'Uasin Gishu',
  'Vihiga',
  'Wajir',
  'West Pokot',
];

export const COUNTY_LOCATION_DIRECTORY = {
  Nairobi: {
    defaultTown: 'Nairobi CBD',
    postalCode: '00100',
    towns: [
      { name: 'Nairobi CBD', postalCode: '00100' },
      { name: 'Westlands', postalCode: '00800' },
      { name: 'Karen', postalCode: '00502' },
      { name: 'Embakasi', postalCode: '00515' },
      { name: 'Eastleigh', postalCode: '00100' },
    ],
  },
  Mombasa: {
    defaultTown: 'Mombasa Island',
    postalCode: '80100',
    towns: [
      { name: 'Mombasa Island', postalCode: '80100' },
      { name: 'Nyali', postalCode: '80118' },
      { name: 'Likoni', postalCode: '80110' },
      { name: 'Kisauni', postalCode: '80109' },
    ],
  },
  Kiambu: {
    defaultTown: 'Kiambu Town',
    postalCode: '00900',
    towns: [
      { name: 'Kiambu Town', postalCode: '00900' },
      { name: 'Thika', postalCode: '01000' },
      { name: 'Ruiru', postalCode: '00232' },
      { name: 'Juja', postalCode: '01001' },
      { name: 'Kikuyu', postalCode: '00902' },
    ],
  },
  Kisumu: {
    defaultTown: 'Kisumu CBD',
    postalCode: '40100',
    towns: [
      { name: 'Kisumu CBD', postalCode: '40100' },
      { name: 'Kondele', postalCode: '40100' },
      { name: 'Ahero', postalCode: '40101' },
      { name: 'Maseno', postalCode: '40105' },
    ],
  },
  Nakuru: {
    defaultTown: 'Nakuru Town',
    postalCode: '20100',
    towns: [
      { name: 'Nakuru Town', postalCode: '20100' },
      { name: 'Naivasha', postalCode: '20117' },
      { name: 'Gilgil', postalCode: '20116' },
      { name: 'Molo', postalCode: '20106' },
    ],
  },
  Kericho: {
    defaultTown: 'Kericho Town',
    postalCode: '20200',
    towns: [
      { name: 'Kericho Town', postalCode: '20200' },
      { name: 'Litein', postalCode: '20210' },
      { name: 'Sotik', postalCode: '20406' },
      { name: 'Kapkatet', postalCode: '20201' },
    ],
  },
  Nyeri: {
    defaultTown: 'Nyeri Town',
    postalCode: '10100',
    towns: [
      { name: 'Nyeri Town', postalCode: '10100' },
      { name: 'Karatina', postalCode: '10101' },
      { name: 'Othaya', postalCode: '10103' },
      { name: 'Mukurweini', postalCode: '10105' },
    ],
  },
  Bungoma: {
    defaultTown: 'Bungoma Town',
    postalCode: '50200',
    towns: [
      { name: 'Bungoma Town', postalCode: '50200' },
      { name: 'Webuye', postalCode: '50205' },
      { name: 'Kimilili', postalCode: '50206' },
      { name: 'Chwele', postalCode: '50208' },
    ],
  },
  Kitui: {
    defaultTown: 'Kitui Town',
    postalCode: '90200',
    towns: [
      { name: 'Kitui Town', postalCode: '90200' },
      { name: 'Mwingi', postalCode: '90400' },
      { name: 'Mutomo', postalCode: '90206' },
      { name: 'Zombe', postalCode: '90208' },
    ],
  },
  Embu: {
    defaultTown: 'Embu Town',
    postalCode: '60100',
    towns: [
      { name: 'Embu Town', postalCode: '60100' },
      { name: 'Runyenjes', postalCode: '60103' },
      { name: 'Siakago', postalCode: '60104' },
      { name: 'Ishiara', postalCode: '60102' },
    ],
  },
  Machakos: {
    defaultTown: 'Machakos Town',
    postalCode: '90100',
    towns: [
      { name: 'Machakos Town', postalCode: '90100' },
      { name: 'Athi River', postalCode: '00204' },
      { name: 'Mavoko', postalCode: '00204' },
      { name: 'Mwala', postalCode: '90128' },
    ],
  },
  Kajiado: {
    defaultTown: 'Kajiado Town',
    postalCode: '01100',
    towns: [
      { name: 'Kajiado Town', postalCode: '01100' },
      { name: 'Ngong', postalCode: '00211' },
      { name: 'Kitengela', postalCode: '00241' },
      { name: 'Isinya', postalCode: '00209' },
    ],
  },
  Kakamega: {
    defaultTown: 'Kakamega Town',
    postalCode: '50100',
    towns: [
      { name: 'Kakamega Town', postalCode: '50100' },
      { name: 'Mumias', postalCode: '50102' },
      { name: 'Butere', postalCode: '50101' },
      { name: 'Malava', postalCode: '50107' },
    ],
  },
  Migori: {
    defaultTown: 'Migori Town',
    postalCode: '40400',
    towns: [
      { name: 'Migori Town', postalCode: '40400' },
      { name: 'Rongo', postalCode: '40401' },
      { name: 'Awendo', postalCode: '40402' },
      { name: 'Isebania', postalCode: '40403' },
    ],
  },
  Narok: {
    defaultTown: 'Narok Town',
    postalCode: '20500',
    towns: [
      { name: 'Narok Town', postalCode: '20500' },
      { name: 'Kilgoris', postalCode: '40700' },
      { name: 'Mau Narok', postalCode: '20505' },
      { name: 'Suswa', postalCode: '20506' },
    ],
  },
  'Taita-Taveta': {
    defaultTown: 'Voi',
    postalCode: '80300',
    towns: [
      { name: 'Voi', postalCode: '80300' },
      { name: 'Mwatate', postalCode: '80301' },
      { name: 'Taveta', postalCode: '80302' },
      { name: 'Wundanyi', postalCode: '80303' },
    ],
  },
  'Tana River': {
    defaultTown: 'Hola',
    postalCode: '70101',
    towns: [
      { name: 'Hola', postalCode: '70101' },
      { name: 'Garsen', postalCode: '70104' },
      { name: 'Bura', postalCode: '70107' },
      { name: 'Madogo', postalCode: '70106' },
    ],
  },
  'Trans Nzoia': {
    defaultTown: 'Kitale',
    postalCode: '30200',
    towns: [
      { name: 'Kitale', postalCode: '30200' },
      { name: 'Kiminini', postalCode: '30201' },
      { name: 'Endebess', postalCode: '30202' },
      { name: 'Kachibora', postalCode: '30203' },
    ],
  },
  Turkana: {
    defaultTown: 'Lodwar',
    postalCode: '30500',
    towns: [
      { name: 'Lodwar', postalCode: '30500' },
      { name: 'Kakuma', postalCode: '30501' },
      { name: 'Lokichoggio', postalCode: '30502' },
      { name: 'Kalokol', postalCode: '30503' },
    ],
  },
  'Uasin Gishu': {
    defaultTown: 'Eldoret',
    postalCode: '30100',
    towns: [
      { name: 'Eldoret', postalCode: '30100' },
      { name: 'Turbo', postalCode: '30106' },
      { name: 'Moiben', postalCode: '30109' },
      { name: 'Ziwa', postalCode: '30110' },
    ],
  },
  Meru: {
    defaultTown: 'Meru Town',
    postalCode: '60200',
    towns: [
      { name: 'Meru Town', postalCode: '60200' },
      { name: 'Maua', postalCode: '60600' },
      { name: 'Nkubu', postalCode: '60202' },
      { name: 'Timau', postalCode: '60400' },
    ],
  },
  Makueni: {
    defaultTown: 'Wote',
    postalCode: '90300',
    towns: [
      { name: 'Wote', postalCode: '90300' },
      { name: 'Makindu', postalCode: '90138' },
      { name: 'Kibwezi', postalCode: '90137' },
      { name: 'Mtito Andei', postalCode: '90129' },
    ],
  },
};

export const getCountyLocationProfile = (county) => COUNTY_LOCATION_DIRECTORY[county] || null;
